innovative/Recipes/urls.py
from django.urls import path
from . import views

app_name='Recipies'

urlpatterns=[
    path('',views.index,name='index'),
    path('recipie/<int:recipie_id>/',views.detail,name='detail'),
    path('add/',views.add_recipie,name="add_recipie"),
    path('update/<int:id>/',views.update,name="update"),
    path('delete/<int:id>/',views.delete,name='delete'),
    # path('review/<int:id>/',views.review,name='review'),

]

innovative/credentials/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register', views.register ,name="register"),
    path('log',views.log,name='log'),
    path('logout',views.logout,name='logout')
]

innovative/innovative/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Recipes.urls')),
    path('search',include('search_app.urls')),
    path('credentials',include('credentials.urls')),
    path('ratings/',include('star_ratings.urls')),


]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


innovative/search_app/urls.py
from django . urls import path
from . import views
app_name='search_app'
urlpatterns = [
    path("",views.searchresult,name='searchresult'),
]

innovative/Recipes/models.py
from django.db import models

# Create your models here.
class Recipie(models.Model):
    name=models.CharField(max_length=200)
    slug=models.SlugField(max_length=250,unique=True)
    prep_time=models.IntegerField()
    Image=models.ImageField(upload_to='product',blank=True)
    difficulty=models.CharField(max_length=500)
    vegetarian=models.BooleanField(default=True)



    class Meta:
        ordering=('name',)
        verbose_name='recipie'
        verbose_name_plural='recipies'
    def __str__(self):
        return self.name

innovative/credentials/models.py
from django.db import models

# Create your models here.

innovative/search_app/models.py
from django.db import models

# Create your models here.

innovative/Recipes/forms.py
from dataclasses import field, fields
from django import forms
from . models import Recipie
class recipie_form(forms.ModelForm):
    class Meta:
        model=Recipie
        fields=['name','prep_time','difficulty','Image','vegetarian']

innovative/Recipes/views.py
from django.shortcuts import render,redirect
from . models import Recipie
from . forms import recipie_form
from django .core . paginator import Paginator,EmptyPage,InvalidPage
from django .contrib.auth.models import User


# Create your views here.

def index(request):
    recipie=Recipie.objects.all()
    paginator=Paginator(recipie,8)
    try:
        page= int(request.GET.get('page','1'))
    except:
        page=1
    try:
        recipies=paginator.page(page)
    except (EmptyPage,InvalidPage):
        recipies=paginator.page(paginator.num_pages)
  
    return render(request,'index.html',{'recipies':recipies})

def detail(request,recipie_id):
    recipies=Recipie.objects.get(id=recipie_id)

    return render(request,'detail.html',{'recipies':recipies})
def add_recipie(request):

    if request.method=="POST":
        name=request.POST.get('name')
        difficulty=request.POST.get('difficulty')
        prep_time=request.POST.get('prep_time')
        Image=request.FILES['Image']
        recipies=Recipie(name=name,difficulty=difficulty,prep_time=prep_time,Image=Image)
        recipies.save()
        return redirect('/')

    
    return render(request,'add.html')

def update(request,id):
    recipies=Recipie.objects.get(id=id) 
    form=recipie_form(request.POST or None,request.FILES,instance=recipies)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request,'edit.html',{'form':form,'recipies':recipies})
def delete(request,id):
    if request.method=="POST":
        recipies=Recipie.objects.get(id=id)
        recipies.delete()
        return redirect('/')
    return render (request,'delete.html')
# def review(request):
#     id=request.GET.get('id')
#     recipie=Recipie.objects.get(id=int(id)) 
#     user=request.session['name']
#     if request.method == 'POST':
#         star_rating=request.POST.get('rating')
#         recipie_review=request.POST.get('recipie_review')
#         recipie_review=review(user)
    # return render(request,'review.html')

innovative/credentials/views.py
from pyexpat.errors import messages
from django.shortcuts import redirect, render
from django .http import HttpResponse
from django .contrib.auth.models import User
from django.contrib import messages,auth
from django.contrib.auth import authenticate



# Create your views here.
def log(request):
    if request.method== 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'invalid user')
            return redirect('log')
    return render(request,'log.html')
def register(request):
    if request.method=='POST':
        username=request.POST['username']
        firstname=request.POST['first name']
        email=request.POST['email']
        password=request.POST['password']
        conpassword=request.POST['password2']
        if password==conpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,'username taken')
                return redirect ("register")
            elif User.objects.filter(email=email).exists():
                messages.info(request,'email taken')
                return redirect('register')
        
            else:


                user=User.objects.create_user(username=username,password=password,email=email)
                user.save() 
                return redirect('log')
        else:
            messages.info(request,'password not matching')
            return redirect("register")
        return redirect('/')

    return render(request,'register.html')
def logout(request):
    auth.logout(request)
    return redirect('/')    

innovative/search_app/views.py
from django.shortcuts import render
from  Recipes .models import Recipie 
from django .db.models import Q
from django.http import HttpResponse
# Create your views here.
def searchresult(request):
    if request.method=='POST':
        searched = request.POST['searched']
        recipies=Recipie.objects.filter(name__contains=searched)

        return render(request,'search.html',{'searched':searched,'recipies':recipies})
    else:
        return render(request,'search.html',)



innovative/templates/add.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>


    <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'Recipies:index'%}">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <form class="d-flex" action="{% url 'search_app:searchresult' %}"  method="POST">
          {% csrf_token %} 
          <input class="form-control me-2" type="search" placeholder="Search" name="searched" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      
    </div>
  </nav>
  {% if user.is_authenticated %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col">
              <input type="text" name="name" class="form-control" placeholder="enter recipie name">
            </div>
            <div class="col">
              <input type="text" name="difficulty" class="form-control" placeholder="difficulty">
            </div>
            <div class="col">
                <input type="number" name="prep_time" class="form-control" placeholder="preparation time">
              </div>
              <div class="col">
              </div>
              <div class="col">
                <input type="file" name="Image" class="form-control">
              </div>
              
          </div>
          
        
        </div>
        <div class="sub">
          <div class="abcd">
            <input type="submit" style="color:blue; width:120px;height:50px; margin-top:10px;margin-left:500px;background-color:black;">
          </div>
        </div> 
    </form>
    {% else %}
    <div class="login"><h1> ADMIN ONLY ALOWED TO CHANGE DATA PLEASE LOGIN ADMIN AND THEN TRY THIS URL</h1></div>
    {% endif %}
</body>
</html>

innovative/templates/delete.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</head>
<body>
    {% if user.is_authenticated %}
    <form method="POST">
        {%csrf_token %}
        ARE YOU SURE YOU WANT TO DELETE RECIPIE 
        <input type="submit">
    </form>
    {% else %}
    <div class="login"><h1> ADMIN ONLY ALOWED TO CHANGE DATA PLEASE LOGIN ADMIN AND THEN TRY THIS UR</h1></div>
    {% endif %}
    
</body>
</html>

innovative/templates/detail.html

{% load static %}
{% load ratings %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <title>Document</title>
    <style>
      .checked {
        color: orange;
      }
      </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'Recipies:index'%}">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <form class="d-flex" action="{% url 'search_app:searchresult' %}"  method="POST">
          {% csrf_token %} 
          <input class="form-control me-2" type="search" placeholder="Search" name="searched" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      
    </div>
  </nav>
  <div class="container">
    <div class="row" >
      <div class="col-md-6"  style="width: 50%; height: 200px; ">
        <img class="card-img-top" src='{{recipies.Image.url}}'  alt="Card image cap">

      </div>
      <div class="col-md-6" style="width: 50%; float: left;">
        <h5 class="card-title">{{recipies.name}}</h5>
        <p class="card-text">difficulty: {{recipies.difficulty}}</p>
        <p class="card-text">preparation time: {{recipies.prep_time}}</p>
        <p class="card-text">vegetarian: {{recipies.vegetarian}}</p>
        <div class="star" style="margin-top: 100px;">
            <h2>Star Rating</h2>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
    

</div>

        
        
      </div>
    </div>
</div>


</body>
</html>

innovative/templates/edit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'Recipies:index'%}">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <form class="d-flex" action="{% url 'search_app:searchresult' %}"  method="POST">
              {% csrf_token %} 
              <input class="form-control me-2" type="search" placeholder="Search" name="searched" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          
        </div>
    </nav>
    {% if user.is_authenticated %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type='submit'>
    </form>
    {% else %}
    <div class="login"><h1> ADMIN ONLY ALOWED TO CHANGE DATA PLEASE LOGIN ADMIN AND THEN TRY THIS UR</h1></div>
    {% endif %}
</body>
</html>

innovative/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'Recipies:index'%}">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <form class="d-flex" action="{% url 'search_app:searchresult' %}"  method="POST">
              {% csrf_token %} 
              <input class="form-control me-2" type="search" placeholder="Search" name="searched" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          
        </div>
      </nav>
      <div class="container ">
        <div class="row">
          {% for i in recipies.object_list %}
          <div class="col-md-3">
            <div class="card" style="margin-top: 20px;">
              <a href="{% url 'Recipies:detail' i.id %}"><img class="card-img-top" src="{{i.Image.url}}"  width="100" height="200" alt="Card image cap">
              <h3 style="background-color: brown;">{{i.name}}</h3></a>
              
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="mx-auto" style="margin-top: 20px;">
          {% if recipies.paginator.num_pages > 1 %}
          <div class="text-center">
            {% for pg in recipies.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm"{% if recipies.number == pg %}active{% endif %}>{{pg}}</a>
            {% endfor %}
          </div>
          {% endif %}

        </div>
        <br>
        
      </div>
      
    
</body>
</html>

innovative/templates/log.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
form {border: 3px solid #f1f1f1;}

input[type=text], input[type=password] {
  width: 50%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
  
}

button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 20%;
  text-align:center;
}

button:hover {
  opacity: 0.8;
}

.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}

.imgcontainer {
  text-align: center;
  
}

img.avatar {
  width: 40%;
  border-radius: 20%;
}

.container {
  padding: 16px;
  text-align:center;
}

span.psw {
  float: right;
  padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: none;
  }
 
}
</style>
</head>
<body>

<h2 style="text-align:center;">welcome  </h2>

<form action="log" method="POST">
  {% csrf_token %}
  

  <div class="container">
    <label for="user name"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" required><br>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required><br>
        
    <button type="submit">Login</button>
   
</form>

</body>
</html>

innovative/templates/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'Recipies:index'%}">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <form class="d-flex" action="{% url 'search_app:searchresult' %}"  method="POST">
          {% csrf_token %} 
          <input class="form-control me-2" type="search" placeholder="Search" name="searched" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      
    </div>
  </nav>
    {% if searched %}
    {% for recipies in recipies %}
    <div class="container" >
        <div class="row" >
          <div class="col-md-6 top" style="width: 50%; height:400px ;">
            <img class="card-img-top" src='{{recipies.Image.url}}' alt="Card image cap">
    
          </div>
        <div class="col-md-6 side" tyle="width: 50%; float: left;">
            <h5 class="card-title">{{recipies.name}}</h5>
            <p class="card-text">{{recipies.difficulty}}</p>
            <p class="card-text">{{recipies.prep_time}}</p>
            <p class="card-text">{{recipies.vegetarian}}</p>
    
            
            
        </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h1>no result</h1>
    {% endif %}
    
          
</body>
</html>